### ISSUE TITLE
AntdTable Inline style has less priority than default

### ISSUE THREAD

**Issue by PaleNeutron** [CNFeffery/feffery-antd-components#124]
If I set `style={"fontSize": 8},` in `fac.AntdTable`, it will not work.  The rule below have hightest priority:

```css
:where(.css-1adbn6x).ant-table-wrapper .ant-table.ant-table-small {
    font-size: 14px;
}
```
